Demar/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls', namespace='main')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,  document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,  document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('',views.index, name='index'),
    path('contact/',views.contact,name='contact'),
    path('plitki/',views.plitki,name='plitki'),
    path('gallery/',views.gallery,name='gallery'),
    path('cart/',views.cart,name='cart'),
    path('laminat/',views.laminat,name='laminat'),
    path('cart-create/',views.cart_create,name='cart_create'),
    path('cart-update/',views.cart_update,name='cart_update'),
    path('cart-delete/',views.cart_delete,name='cart_delete'),
    path("order/", views.order, name="order"),
    path("orderview/", views.orderView, name="orderview"),
]

main/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

# Create your models here.
class Question(models.Model):
	name = models.CharField('Ismi',max_length=250,)
	phone = models.CharField('Telefon ', max_length=50)
	message = models.CharField('Xabari', max_length=250)

	class Meta:
		verbose_name = 'Savol'
		verbose_name_plural = 'Savollar'

	def __str__(self):
		return f"{self.name}"
class Contact(models.Model):
	name = models.CharField('Ismi',max_length=250,)
	phone = models.CharField('Telefon ', max_length=50)
	email = models.EmailField('Emaili', max_length=250)

	class Meta:
		verbose_name = 'Aloqa'
		verbose_name_plural = 'Aloqalar'

	def __str__(self):
		return f"{self.name}"


class Category(models.Model):
    name = models.CharField('Nomi',max_length=150,)
    slug = models.SlugField('*',max_length=150, unique=True)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:category_detail', kwargs={'category_slug':self.slug})

class Product(models.Model):
    category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='product_images/',blank=True)
    description = models.TextField(blank=True)
    price = models.FloatField()
    old_price = models.PositiveIntegerField('Avvalgi Narxi',default=0)
    available = models.BooleanField(default=True)
    instock = models.BooleanField('Bor / Yok', default=True)
    created = models.DateTimeField(default=timezone.now)
    updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
    
    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail',args=[str(self.slug)])


class Cart(models.Model):
    product = models.ForeignKey("main.Product", verbose_name="cart of product", on_delete=models.CASCADE)
    mkv = models.FloatField("m kvadrat")
    all_price = models.FloatField()

    def __str__(self):
        return f"{self.product.name}, --{self.mkv}"


class MainCart(models.Model):
    carts =  models.ManyToManyField(Cart, verbose_name="carts", blank=True)
    all_price = models.FloatField(default=0)

    def __str__(self):
        return str(self.carts.all().count())


class Order(models.Model):
    first_name = models.CharField("Ismi", max_length=50)
    last_name = models.CharField("familiyasi", max_length=50)
    phone = models.PositiveIntegerField("phone")
    cart = models.ForeignKey(MainCart, verbose_name="carts", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.first_name}, {self.last_name}"

main/views.py
from multiprocessing import context
from django.shortcuts import get_object_or_404, render,redirect
from .models import *
from django.contrib import messages
from django.template import RequestContext
from django.http import JsonResponse, request
from django.contrib.auth.models import User

def index(request):
	products = Product.objects.all().order_by('-id')
	if request.method == 'POST':
		name = request.POST['name']
		phone = request.POST['phone']
		message = request.POST['message']
		Question.objects.create(name=name,phone=phone,message=message)	
	return render(request,'index.html',{'products':products})

def contact(request):
	if request.method == 'POST':
		name = request.POST['name']
		phone = request.POST['phone']
		email = request.POST['email']
		Contact.objects.create(name=name,phone=phone,email=email)	
	return render(request,'contact.html')

def cart(request):
	main = request.session['cart']
	cart = get_object_or_404(MainCart, id=int(main))
	context = {
		'cart':cart,
	}
	return render(request,'cart.html', context)

def plitki(request):
	return render(request,'catalogStone.html')

def laminat(request):
	return render(request,'catalogLaminat.html')

def gallery(request):
	return render(request,'gallery.html')

# cart block

def mainCartCreate(request):
	try:
		print(request.session['cart'])
	except:
		cart = MainCart.objects.create()
		request.session['cart'] = cart.id
		print('cart created')

	return request


def cart_create(request):
	main = request.session['cart']
	product_id = request.GET.get('product_id')
	mkv = request.GET.get('mkv')
	product = Product.objects.get(id=product_id)
	all_price = float(mkv)*float(product.price)
	new = Cart.objects.create(
		product=product,
		mkv=float(mkv),
		all_price=all_price
	)
	mainCart = MainCart.objects.get(id=main)
	if new not in mainCart.carts.all():
		mainCart.carts.add(new)
		a = 0.0
		for i in mainCart.carts.all():
			a += i.all_price
		mainCart.all_price = a
		mainCart.save()
	return JsonResponse({'data':'created'})

def cart_update(request):
	main = request.session['cart']
	mkv = request.GET.get('mkv')
	cart_id = request.GET.get('cart_id')
	cart = Cart.objects.get(id=int(cart_id))
	price = cart.product.price*float(mkv)
	cart.all_price = price
	cart.mkv = mkv
	cart.save()
	mainCart = MainCart.objects.get(id=main)
	a = 0.0
	for i in mainCart.carts.all():
		a += i.all_price
	mainCart.all_price = a
	mainCart.save()
	return JsonResponse({
		'price':cart.all_price,
		'main_price':mainCart.all_price
		})

def cart_delete(request):
	main = request.session['cart']
	cart_id = request.GET.get('cart_id')
	cart = Cart.objects.get(id=int(cart_id))
	cart.delete()
	mainCart = MainCart.objects.get(id=main)
	a = 0.0
	for i in mainCart.carts.all():
		a += i.all_price
	mainCart.all_price = a
	mainCart.save()
	return JsonResponse({'main_price':mainCart.all_price})

import telebot
TOKEN = '5189245732:AAHLRbxCGDZmrZZtUQaEgPWQTcuSS3IACGQ'
chat_id = 1257603816
tb = telebot.TeleBot(TOKEN)


def order(request):
	main = request.session['cart']
	mainCart = MainCart.objects.get(id=main)
	name = request.GET.get('name')
	surname = request.GET.get('surname')
	phone = request.GET.get('phone')
	if mainCart.carts:
		order = Order.objects.create(
			first_name=name,
			last_name=surname,
			phone=int(phone),
			cart=mainCart
		)
		message = f"Ismi: {order.first_name}\nFamiliyasi: {order.last_name}\nTelefon raqami: {order.phone}\nTovarlar: \n"
		for i in order.cart.carts.all():
			message += f"{i}m kvadrat\n"
		message += f"Jami narxi: {order.cart.all_price} so'm"
		tb.send_message(chat_id, message)
	return redirect('/orderview/')


def orderView(request):
	return render(request, 'order.html')

templates/cart.html
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="/static/fontawesome-free-5.15.4-web/css/all.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Cart</title>
    <link rel="stylesheet" href="/static/css/cart.css" />
  </head>
  <body>
    <header id="navbar">
      <a href="{% url 'main:index' %}"><img class="logo" src="/static/images/logo.png" alt="" /></a> 
        <div class="btn-hamburger" id="burger">
          <div id="drop-men" class="dropdown">
            <a data-toggle="dropdown"><i class="fas fa-bars"></i></a>
            <ul
              style="background-color: black; margin-left: -10px"
              id="drop-menu"
              class="dropdown-menu"
              role="menu"
              aria-labelledby="dLabel"
            >
              <div class="dropdow">
                <li><a href="{% url 'main:contact' %}">Контакты</a></li>
              </div>
              <hr />
              <div class="dropdow">
                <li><a href="gallery.html">Галерея</a></li>
              </div>
            </ul>
          </div>
        </div>
        <ul class="header" id="ul">
          <li><a href="{% url 'main:contact' %}">Контакты</a></li>
          <li><a href="gallery.html">Галерея</a></li>
        </ul>
        <div class="li-cen">
          <li class="glry">
            <div class="dropdown">
              <a style="color: #fff;"class="dropdown-toggle" data-toggle="dropdown">Каталог</a>
              <ul
                id="dropdown-menu"
                class="dropdown-menu"
                role="menu"
                aria-labelledby="dLabel"
              >
                <div class="dropdowns">
                  <h1 class="stoness"><a style="color: black;" href="{% url 'main:plitki' %}">Плитки</a></h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/stones.png"
                    alt=""
                  />
                </div>
                <hr class="hri" />
                <div class="dropdowns">
                  <h1 class="laminate">
                    <a style="color: black;" href="{% url 'main:laminat' %}">Пракет/ламинат</a>
                  </h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/laminates.png"
                    alt=""
                  />
                </div>
              </ul>
            </div>
          </li>
        </div>
        <div class="navbar-end">
          <a href="cart.html"
            ><img class="cart" src="/static/images/cart.png" alt=""
          /></a>
          <button type="button" class="search-btn">
            <img class="search" src="/static/images/search.png" alt="" />
          </button>
        </div>
      </header>

    <div class="white">
      <button type="button" class="clear-btn">
        <img class="cleo" src="./images/clear.png" alt="" />
      </button>
      <div class="white-div">
        <input type="text" class="white-input" />
      </div>
      <h1 class="white-text">Найдено (0)</h1>
    </div>

    <div class="cart-section">
      <h2 class="cart-text">Моя корзина</h2>
      <h6 class="cart-title">
        В корзине <span style="color: #f5b282">{{cart.carts.all.count}} товаров</span>
      </h6>
      <div class="carts">
        
        {% for carts in cart.carts.all %}
        <div class="carte">
          <div class="cart-cart">
            <div class="cartes" style="margin-top: 39px">
              <img class="stone" src="{{carts.product.image.url}}" alt="" />
              <h1 class="cart-cart-text">{{carts.product.name}}</h1>
            </div>
            <div>
              <button type="button" class="delete" data-id="{{carts.id}}"><img class="krestik" src="/static/images/clear.png" alt="" /></button>
            </div>
          </div>
          <div class="cart-in">
            <div>
              <h4 class="cart-in-text">Цена (m2)</h4>
              <h4 class="cart-in-title">{{carts.product.price}} сум</h4>
            </div>
          </div>
          <div class="cart-on">
            <div style="margin-right: 40px">
              <h4 class="cart-on-text">Количество (m2)</h4>
              <div style="display: flex">
                <input data-id="{{carts.id}}" type="number" class="mkv" value="{{carts.mkv}}">
                <h6 style="margin-left: 20px;"> Итого:</h6>
                <h4 class="cart-on-title"><b class="price">{{carts.all_price}}</b> сум</h4>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
          
        
        
      </div>
      <div class="all-price">Итого: <b class="all">{{cart.all_price}}</b> сум</div>
      <div style="text-align: center">
        <a href="order.html"><button type="button" class="cart-btn">Оформить заказ</button></a>
      </div>
    </div>

 <div class="mapouter">
  <div class="gmap_canvas">
    <iframe width="100%" height="600" id="gmap_canvas" src="https://maps.google.com/maps?q=2880%20Broadway,%20New%20York&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
    <a href="https://fmovies-online.net">

    </a>
    <br>

    </div>
  </div>

    <div class="footer-section">
      <div class="footers">
        <div class="footer-left">
          <img class="logofooter" src="./images/ащщеукдщпщ.png" alt="" />
          <h6 class="copy">©Demar 2021</h6>
        </div>
        <div class="footer-center">
          <h1 class="footer-text"><a style="color: #fff;" href="contact.html">Контакт</a></h1>
          <h1 class="footer-text"><a style="color: #fff;" href="gallery.html">Галерея</a></h1>
          <h1 class="footer-text">
            <a style="color: #fff;" href="catalogLaminat.html">Ламинат/Паркет</a>
          </h1>
          <h1 class="footer-text"><a style="color: #fff; " href="catalogStone.html"> Кафель </a></h1>
        </div>
        <div class="footer-right">
          <h2 class="footer-phone">+998 (99) 555-25-89</h2>
          <div class="footer-left-first">
            <h2 class="footer-title">Адрес</h2>
            <h6 class="footer-para">Чиланзарский район, 8 улица Аль-Хорезми</h6>
          </div>
          <div>
            <h2 class="footer-title">E-mail</h2>
            <h6 class="footer-para">Demar.support.gmail.com</h6>
          </div>
        </div>
      </div>
    </div>

    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script src="/static/script.js"></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
  </body>
</html>
{% endblock%}

templates/catalogLaminat.html
<!DOCTYPE html>
{% load static %}
{% block content %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="./fontawesome-free-5.15.4-web/css/all.min.css"
      rel="stylesheet"
    />
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
      crossorigin="anonymous"
    ></script>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
      crossorigin="anonymous"
    />
    <title>Каталог</title>
    <link rel="stylesheet" href="/static/css/catalogStone.css" />
  </head>
  <body>
    <header id="navbar">
<a href="{% url 'main:index' %}"><img class="logo" src="/static/images/logo.png" alt="" /></a> 
        <div class="btn-hamburger" id="burger">
          <div id="drop-men" class="dropdown">
            <a data-toggle="dropdown"><i class="fas fa-bars"></i></a>
            <ul
              style="background-color: black; margin-left: -10px"
              id="drop-menu"
              class="dropdown-menu"
              role="menu"
              aria-labelledby="dLabel"
            >
              <div class="dropdow">
                <li><a href="{% url 'main:contact' %}">Контакты</a></li>
              </div>
              <hr />
              <div class="dropdow">
                <li><a href="gallery.html">Галерея</a></li>
              </div>
            </ul>
          </div>
        </div>
        <ul class="header" id="ul">
          <li><a href="{% url 'main:contact' %}">Контакты</a></li>
          <li><a href="gallery.html">Галерея</a></li>
        </ul>
        <div class="li-cen">
          <li class="glry">
            <div class="dropdown">
              <a style="color: #fff;"class="dropdown-toggle" data-toggle="dropdown">Каталог</a>
              <ul
                id="dropdown-menu"
                class="dropdown-menu"
                role="menu"
                aria-labelledby="dLabel"
              >
                <div class="dropdowns">
                  <h1 class="stoness"><a style="color: black;" href="{% url 'main:plitki' %}">Плитки</a></h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/stones.png"
                    alt=""
                  />
                </div>
                <hr class="hri" />
                <div class="dropdowns">
                  <h1 class="laminate">
                    <a style="color: black;" href="{% url 'main:laminat' %}">Пракет/ламинат</a>
                  </h1>
                  <img
                    class="drop-img"
                    width="193px"
                    height="117px"
                    src="/static/images/laminates.png"
                    alt=""
                  />
                </div>
              </ul>
            </div>
          </li>
        </div>
        <div class="navbar-end">
          <a href="{% url 'accounts:register' %}"
            ><img class="user" src="/static/images/user.png" alt=""
          /></a>
          <a href="cart.html"
            ><img class="cart" src="/static/images/cart.png" alt=""
          /></a>
          <button type="button" class="search-btn">
            <img class="search" src="/static/images/search.png" alt="" />
          </button>
        </div>
      </header>

    <div class="white">
      <button type="button" class="clear-btn">
        <img class="cleo" src="/static/images/clear.png" alt="" />
      </button>
      <div class="white-div">
        <input type="text" class="white-input" />
      </div>
      <h1 class="white-text">Найдено (0)</h1>
    </div>

    <div class="catalog-section">
      <h1 class="catalog-text">Каталог</h1>
      <div class="catalog-div">
        <div class="catalog-first-div">
          <h1 class="catalog-div-text">Тип товара</h1>
          <div class="btns-cata">
            <a href="catalogStone.html"
              ><button type="button" class="laminat-btn">Плитка</button></a
            >
            <a href="catalogLaminat.html"
              ><button type="button" class="plitka-btn">
                Ламинат/паркет
              </button></a
            >
          </div>
        </div>
        <div class="catalog-second-div">
          <select
            id="select"
            class="form-select"
            aria-label="Default select example"
          >
            <option selected>Рекомендуемые</option>
            <option value="1">Высокая цена</option>
            <option value="2">Низкая цена</option>
          </select>
        </div>
      </div>

      <div class="catalogs">
        <div class="catalog">
          <button type="button" class="catalog-btn">
            Фильтр<img class="upper" src="/static/images/up.png" alt="" />
          </button>
          <div class="catalog-hid">
            <div class="sum-section">
              <h1 class="sum-text">Цена</h1>
              <input type="text" class="catalog-input" placeholder="от" />
              <input type="text" class="catalog-input" placeholder="до" />
            </div>
            <div class="format-section">
              <h1 class="sum-text">Порода дерева</h1>
              <div class="checkboxes" style="height: 150px">
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">Бук</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">Вишня</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">Буд</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">Мербау</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">Орех</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">Ясень</h1>
                </div>
              </div>
            </div>
            <div class="colors-div">
              <h1 class="sum-text">Тон</h1>
              <div class="checkboxes" style="height: 205px">
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <span class="colors" style="background-color: #bdbdbd"></span>
                  <h1 class="check-text">Бежевый</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <span class="colors" style="border: 1px solid"></span>
                  <h1 class="check-text">Белый</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <span class="colors" style="background-color: #964b00"></span>
                  <h1 class="check-text">Коричневый</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <span class="colors" style="background-color: #808080"></span>
                  <h1 class="check-text">Серый</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <span class="colors" style="background-color: #000"></span>
                  <h1 class="check-text">Тёмный</h1>
                </div>
              </div>
            </div>
            <div class="num-div">
              <h1 class="sum-text">Количество полос</h1>
              <div class="checkboxes" style="height: 150px">
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">1-полосная</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">2-полосная</h1>
                </div>
                <div style="display: flex">
                  <input type="checkbox" class="checks" />
                  <h1 class="check-text">3-полосная</h1>
                </div>
              </div>
            </div>
            <div
              style="
                display: flex;
                justify-content: space-between;
                width: 300px;
                margin-top: 60px;
              "
            >
              <h1 class="clear-text">Сбросить фильтр</h1>
              <img class="clear-img" src="/static/images/x.png" alt="" />
            </div>
          </div>
        </div>
        <div class="catalog">
          <div class="stones">
            {% for pro in products %}
            <div class="stone">
              <div>
                <span class="sale">-20%</span>
                <img class="stone-img" src="{{po.image.url}}" alt="" />
              </div>
              <div class="stone-div">
                <span class="stone-price">{{pro.price}}</span
                ><span class="stone-sum">сум/m²</span>
                <span class="stone-old">{{pro.old_price}}</span
                ><span class="stone-sums">сум/m²</span>
              </div>
              <div class="stone-di">
                <h4 class="stone-text">Boost Pro 3D Urban</h4>
                <h4 class="stone-title">Ergon (Италия)</h4>
              </div>
              <p class="stone-para">
                Плитка Laparet Calacatta Oro 60x120, золотая, полированная
              </p>
              <div class="stone-d">
                <button type="button" class="stone-btn">
                  <img src="/static//images/shopping.png" alt="" />
                </button>
                <img class="fav" src="/static/images/favorite.png" alt="" />
              </div>
            </div>
           {% endfor %}
          </div>
          <div
            style="margin-left: auto; margin-right: auto; text-align: center"
          >
            <button type="button" class="more-btn">Показать больше</button>
          </div>
        </div>
      </div>
    </div>

   <div class="mapouter">
  <div class="gmap_canvas">
    <iframe width="100%" height="600" id="gmap_canvas" src="https://maps.google.com/maps?q=2880%20Broadway,%20New%20York&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
    <a href="https://fmovies-online.net">

    </a>
    <br>

    </div>
  </div>

    <<div class="footer-section">
      <div class="footers">
        <div class="footer-left">
          <img class="logofooter" src="/static/images/ащщеукдщпщ.png" alt="" />
          <h6 class="copy">©Demar 2021</h6>
        </div>
        <div class="footer-center">
          <h1 class="footer-text"><a style="color: #fff;" href="contact.html">Контакт</a></h1>
          <h1 class="footer-text"><a style="color: #fff;" href="gallery.html">Галерея</a></h1>
          <h1 class="footer-text">
            <a style="color: #fff;" href="catalogLaminat.html">Ламинат/Паркет</a>
          </h1>
          <h1 class="footer-text"><a style="color: #fff; " href="catalogStone.html"> Кафель </a></h1>
        </div>
        <div class="footer-right">
          <h2 class="footer-phone">+998 (99) 555-25-89</h2>
          <div class="footer-left-first">
            <h2 class="footer-title">Адрес</h2>
            <h6 class="footer-para">Чиланзарский район, 8 улица Аль-Хорезми</h6>
          </div>
          <div>
            <h2 class="footer-title">E-mail</h2>
            <h6 class="footer-para">Demar.support.gmail.com</h6>
          </div>
        </div>
      </div>
    </div>

    <script src="/static/script.js"></script>
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx"
      crossorigin="anonymous"
    ></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"
      integrity="sha512-HGOnQO9+SP1V92SrtZfjqxxtLmVzqZpjFFekvzZVWoiASSQgSr4cw9Kqd2+l8Llp4Gm0G8GIFJ4ddwZilcdb8A=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    ></script>
  </body>
</html>
{% endblock %}